# Generated by Django 2.2.12 on 2020-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ZohoHostedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZohoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField(blank=True, help_text='The raw response, from Zoho', null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
